-- 更新 orders 表，添加新字段
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS product_name TEXT,
ADD COLUMN IF NOT EXISTS buyer_note TEXT,
ADD COLUMN IF NOT EXISTS return_reason TEXT,
ADD COLUMN IF NOT EXISTS inventory_attribute TEXT,
ADD COLUMN IF NOT EXISTS country TEXT,
ADD COLUMN IF NOT EXISTS product_sku TEXT,
ADD COLUMN IF NOT EXISTS msku TEXT,
ADD COLUMN IF NOT EXISTS asin TEXT,
ADD COLUMN IF NOT EXISTS fnsku TEXT,
ADD COLUMN IF NOT EXISTS return_quantity INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS warehouse_quantity INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS return_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS order_time TIMESTAMP WITH TIME ZONE;